[project]
name = "mlops_project"
version = "0.1.0"
dependencies = [
    "pandas",
    "numpy",
    "scikit-learn",
    "dagster",
    "fastapi",
    "uvicorn",
    "mlflow",
    "evidently",
    "pytest",
    "pre-commit"
]
